### ISSUE TITLE
Bard Python Script Broken

### ISSUE THREAD

**Issue by SlykBridge** [knrd1/bard#3]
The python script for Bard does not work anymore since becoming Gemini and now has an error when run:

Traceback (most recent call last):
  File "/home/zuberlan/bard/bard.py", line 20, in <module>
    bard = BardCookies(cookie_dict=cookie_dict)
  File "/home/zuberlan/.local/lib/python3.10/site-packages/bardapi/core_cookies.py", line 53, in __init__
    self.SNlM0e = self._get_snim0e()
  File "/home/zuberlan/.local/lib/python3.10/site-packages/bardapi/core_cookies.py", line 110, in _get_snim0e
    resp = self.session.get(
  File "/home/zuberlan/.local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/zuberlan/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zuberlan/.local/lib/python3.10/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/home/zuberlan/.local/lib/python3.10/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/home/zuberlan/.local/lib/python3.10/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by knrd1** [comment]
Thanks for your message!

Bard IRC Bot relies on this libraery: https://github.com/dsdanielpark/Bard-API

From what I can see, they are currently working on a hotfix; once fixed the bot should be back again: https://github.com/dsdanielpark/Bard-API?tab=readme-ov-file#updates
