### ISSUE TITLE
Bard is now Gemini and bot isn't working

### ISSUE THREAD

**Issue by charls-a** [knrd1/bard#4]
I'm so sad :(

**Comment by knrd1** [comment]
Thanks for your message!

Bard IRC Bot relies on this library: https://github.com/dsdanielpark/Bard-API

From what I can see, they are currently working on a hotfix; once fixed the bot should be back again: https://github.com/dsdanielpark/Bard-API?tab=readme-ov-file#updates

**Comment by charls-a** [comment]
I allready updated bardapi to 0.1.40:

bard@servidor:~/bard$ python3 bard.py
Traceback (most recent call last):
  File "bard.py", line 1, in <module>
    from bardapi import Bard
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/__init__.py", line 4, in <module>
    from bardapi.core import Bard
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/core.py", line 26, in <module>
    from bardapi.models.result import BardResult
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/models/result.py", line 3, in <module>
    from bardapi.models.draft import BardDraft
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/models/draft.py", line 14, in <module>
    from bardapi.models.tools.youtube import BardYoutubeContent
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/models/tools/youtube.py", line 38, in <module>
    class BardYoutubeContent(UserContent):
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/models/tools/youtube.py", line 63, in BardYoutubeContent
    def videos(self) -> list[BardYoutubeVideo]:
TypeError: 'type' object is not subscriptable
bard@servidor:~/bard$

Still not working :(

**Comment by charls-a** [comment]
Updated to bardapi 0.1.41:

bard@servidor:~$ cd bard/
bard@servidor:~/bard$ python3 bard.py
Traceback (most recent call last):
  File "bard.py", line 1, in <module>
    from bardapi import Bard
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/__init__.py", line 4, in <module>
    from bardapi.core import Bard
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/core.py", line 26, in <module>
    from bardapi.models.result import BardResult
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/models/result.py", line 3, in <module>
    from bardapi.models.draft import BardDraft
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/models/draft.py", line 14, in <module>
    from bardapi.models.tools.youtube import BardYoutubeContent
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/models/tools/youtube.py", line 38, in <module>
    class BardYoutubeContent(UserContent):
  File "/home/bard/.local/lib/python3.8/site-packages/bardapi/models/tools/youtube.py", line 63, in BardYoutubeContent
    def videos(self) -> list[BardYoutubeVideo]:
TypeError: 'type' object is not subscriptable
bard@servidor:~/bard$
